services:
    db:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MY_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        volumes:
            - ./database:/docker-entrypoint-initdb.d # соединяем файл инициализации с файлом запуска бд
        ports:
            - 8806:3306

    server:
        container_name: php-apache
        build: ./server/ # указание расположения файла DOCKERFILE для docker-compose
        ports:
            - 8000:80
        volumes:
            - ./server/:/var/www/html/ # соединяем папку с клиентской частью с папкой виртуальной машины
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
        ports:
            - 8080:80
        depends_on:
            - db
    drawer:
        container_name: Drawer
        image: php:7.2-apache
        ports:
            - 1111:80
        volumes:
            - ./drawer:/var/www/html

    sort:
        container_name: sort
        image: php:7.2-apache
        ports:
            - 2222:80
        volumes:
            - ./sort:/var/www/html

    console:
        container_name: console
        image: php:7.2-apache
        ports:
            - 3333:80
        volumes:
            - ./console:/var/www/html
